---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.8

suites:
  - name: sonarqube_server
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[sonarqube]
    attributes:
      java:
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
        jdk:
          '8':
            x86_64:
              url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
              checksum: 97e30203f1aef324a07c94d9d078f5d19bb6c50e638e4492722debca588210bc
  - name: sonarqube_server_mysql
    excludes:
      - ubuntu-12.04
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[sonarqube_mysql]
      - recipe[sonarqube]
    attributes:
      java:
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
        jdk:
          '8':
            x86_64:
              url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
              checksum: 97e30203f1aef324a07c94d9d078f5d19bb6c50e638e4492722debca588210bc
      sonarqube:
        mysqlDatabase:
          host: localhost
          port: '3306'
          database: sonar
  - name: sonarqube_scanner
    run_list:
      - recipe[sonarqube::scanner]
  - name: sonarqube_plugin
    run_list:
      - recipe[apt]
      - recipe[java]
      - recipe[sonarqube]
      - recipe[sonarqube_plugin_consumer]
    attributes:
      java:
        jdk_version: '8'
        oracle:
          accept_oracle_download_terms: true
        install_flavor: oracle
        jdk:
          '8':
            x86_64:
              url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.tar.gz
              checksum: 97e30203f1aef324a07c94d9d078f5d19bb6c50e638e4492722debca588210bc
